In [ ]:
import pandas as pd
import numpy as np
students=pd.DataFrame({
    "Student_ID":[101,102,102,103,104,105],
    "Name":["Astha","Aditi","Aditi","Arjun","Krishna",None],
    "Dept":["CSE","cse","cse","Data Science","DATA SCIENCE","ECI"],
    "Marks":[82,72,72,np.nan,91,88],
    "Attendance":[90,82,82,75,np.nan,88],
    "Exam_Date":["2026-09-01","10-09-2026","01-09-2026","2020-09-02","not known","2026-09-03"]
})
print(students)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [ ]:
students.isna()

   Student_ID   Name   Dept  Marks  Attendance  Exam_Date
0       False  False  False  False       False      False
1       False  False  False  False       False      False
2       False  False  False  False       False      False
3       False  False  False   True       False      False
4       False  False  False  False        True      False
5       False   True  False  False       False      False

In [ ]:
missing_percent=students.isnull().mean()*100/len(students)
print(missing_percent.round(2))

Student_ID    0.00
Name          2.78
Dept          0.00
Marks         2.78
Attendance    2.78
Exam_Date     0.00
dtype: float64

In [ ]:
students.isnull().values.any()

np.True_

In [ ]:
print(students.isna().sum())

Student_ID    0
Name          1
Dept          0
Marks         1
Attendance    1
Exam_Date     0
dtype: int64

Removing Missing Valueswith dropna()

In [ ]:
df_clean=students.dropna()

In [ ]:
students

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [ ]:
df_clean_col=students.dropna(axis=1)

In [ ]:
df_clean_col

   Student_ID          Dept   Exam_Date
0         101           CSE  2026-09-01
1         102           cse  10-09-2026
2         102           cse  01-09-2026
3         103  Data Science  2020-09-02
4         104  DATA SCIENCE   not known
5         105           ECI  2026-09-03

Remove rows only when every value is missing

In [ ]:
df_clean_all=students.dropna(how="all")

In [ ]:
df_clean_all

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

Simple statistical imputation

mean imputation

In [ ]:
from sklearn.impute import SimpleImputer
mean_imputer=SimpleImputer(strategy="mean")
df_mean=students.copy()
df_mean[["Attendance","Marks"]]=mean_imputer.fit_transform(df_mean[["Attendance","Marks"]])
print(df_mean)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science   81.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        83.4   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [ ]:
from sklearn.impute import SimpleImputer
median_imputer=SimpleImputer(strategy="median")
df_median=students.copy()
df_median[["Attendance","Marks"]]=median_imputer.fit_transform(df_median[["Attendance","Marks"]])
print(df_median)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science   82.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        82.0   not known
5         105     None           ECI   88.0        88.0  2026-09-03

Most -frequent-value impulation

In [ ]:
from sklearn.impute import SimpleImputer
mode_imputer=SimpleImputer(missing_values=None,strategy="most_frequent")
df_mode=students.copy()
df_mode[["Name"]]=mode_imputer.fit_transform(df_mode[["Name"]])
print(df_mode)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105    Aditi           ECI   88.0        88.0  2026-09-03

In [ ]:
from sklearn.impute import SimpleImputer
const_imputer=SimpleImputer(strategy="constant",fill_value=0)
df_const=students.copy()
df_const[["Marks","Attendance"]]=const_imputer.fit_transform(df_const[["Marks","Attendance"]])
print(df_const)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    0.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         0.0   not known
5         105     None           ECI   88.0        88.0  2026-09-03

KNN imputation

In [ ]:
from sklearn.impute import KNNImputer
knn_imputer=KNNImputer(n_neighbors=2)
df_knn=students.copy()
df_knn[["Marks","Attendance"]]=knn_imputer.fit_transform(df_knn[["Marks","Attendance"]])
print(df_knn)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science   72.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        89.0   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [ ]:
students

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

Decide how to handle missing values

In [ ]:
clean=students.copy()
clean["Marks"]=clean["Marks"].fillna(clean["Marks"].median())
clean["Attendance"]=clean["Marks"].fillna(clean["Attendance"].median())
clean["Name"]=clean["Name"].fillna("unknown")
print(clean)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        82.0  2026-09-01
1         102    Aditi           cse   72.0        72.0  10-09-2026
2         102    Aditi           cse   72.0        72.0  01-09-2026
3         103    Arjun  Data Science   82.0        82.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        91.0   not known
5         105  unknown           ECI   88.0        88.0  2026-09-03

Remove exact duplicate

In [ ]:
print("Exact duplicates",clean.duplicated().sum())

Exact duplicates 0

In [ ]:
clean

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        82.0  2026-09-01
1         102    Aditi           cse   72.0        72.0  10-09-2026
2         102    Aditi           cse   72.0        72.0  01-09-2026
3         103    Arjun  Data Science   82.0        82.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        91.0   not known
5         105  unknown           ECI   88.0        88.0  2026-09-03

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    "Student_ID":[101,102,102,103,104,105],
    "Name":["Astha","Aditi","Aditi","Arjun","Krishna",None],
    "Dept":["CSE","cse","cse","Data Science","DATA SCIENCE","ECI"],
    "Marks":[82,72,72,np.nan,91,88],
    "Attendance":[90,82,82,75,np.nan,88],
    "Exam_Date":["2026-09-01","10-09-2026","01-09-2026","2020-09-02","not known","2026-09-03"]
})
print(df)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [ ]:
no_exact_duplicates=clean.drop_duplicates()
print("Rows before:",len(clean))
print("Rows after:",len(no_exact_duplicates))

Rows before: 6
Rows after: 6

Remove duplicates using an ID