In [1]:
import pandas as pd
import numpy as np
students=pd.DataFrame({
    "Student_ID":[101,102,102,103,104,105],
    "Name":["Astha","Aditi","Aditi","Arjun","Krishna",None],
    "Dept":["CSE","cse","cse","Data Science","DATA SCIENCE","ECI"],
    "Marks":[82,72,72,np.nan,91,88],
    "Attendance":[90,82,82,75,np.nan,88],
    "Exam_Date":["2026-09-01","10-09-2026","01-09-2026","2020-09-02","not known","2026-09-03"]
})
print(students)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [2]:
students.isna()

   Student_ID   Name   Dept  Marks  Attendance  Exam_Date
0       False  False  False  False       False      False
1       False  False  False  False       False      False
2       False  False  False  False       False      False
3       False  False  False   True       False      False
4       False  False  False  False        True      False
5       False   True  False  False       False      False

In [3]:
missing_percent=students.isnull().mean()*100/len(students)
print(missing_percent.round(2))

Student_ID    0.00
Name          2.78
Dept          0.00
Marks         2.78
Attendance    2.78
Exam_Date     0.00
dtype: float64

In [4]:
students.isnull().values.any()

np.True_

In [5]:
print(students.isna().sum())

Student_ID    0
Name          1
Dept          0
Marks         1
Attendance    1
Exam_Date     0
dtype: int64

Removing Missing Valueswith dropna()

In [6]:
df_clean=students.dropna()

In [7]:
students

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [8]:
df_clean_col=students.dropna(axis=1)

In [9]:
df_clean_col

   Student_ID          Dept   Exam_Date
0         101           CSE  2026-09-01
1         102           cse  10-09-2026
2         102           cse  01-09-2026
3         103  Data Science  2020-09-02
4         104  DATA SCIENCE   not known
5         105           ECI  2026-09-03

Remove rows only when every value is missing

In [10]:
df_clean_all=students.dropna(how="all")

In [11]:
df_clean_all

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

Simple statistical imputation

mean imputation

In [12]:
from sklearn.impute import SimpleImputer
mean_imputer=SimpleImputer(strategy="mean")
df_mean=students.copy()
df_mean[["Attendance","Marks"]]=mean_imputer.fit_transform(df_mean[["Attendance","Marks"]])
print(df_mean)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science   81.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        83.4   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [13]:
from sklearn.impute import SimpleImputer
median_imputer=SimpleImputer(strategy="median")
df_median=students.copy()
df_median[["Attendance","Marks"]]=median_imputer.fit_transform(df_median[["Attendance","Marks"]])
print(df_median)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science   82.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        82.0   not known
5         105     None           ECI   88.0        88.0  2026-09-03

Most -frequent-value impulation

In [14]:
from sklearn.impute import SimpleImputer
mode_imputer=SimpleImputer(missing_values=None,strategy="most_frequent")
df_mode=students.copy()
df_mode[["Name"]]=mode_imputer.fit_transform(df_mode[["Name"]])
print(df_mode)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105    Aditi           ECI   88.0        88.0  2026-09-03

In [15]:
from sklearn.impute import SimpleImputer
const_imputer=SimpleImputer(strategy="constant",fill_value=0)
df_const=students.copy()
df_const[["Marks","Attendance"]]=const_imputer.fit_transform(df_const[["Marks","Attendance"]])
print(df_const)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    0.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         0.0   not known
5         105     None           ECI   88.0        88.0  2026-09-03

KNN imputation

In [16]:
from sklearn.impute import KNNImputer
knn_imputer=KNNImputer(n_neighbors=2)
df_knn=students.copy()
df_knn[["Marks","Attendance"]]=knn_imputer.fit_transform(df_knn[["Marks","Attendance"]])
print(df_knn)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science   72.0        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        89.0   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [17]:
students

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

Decide how to handle missing values

In [18]:
clean=students.copy()
clean["Marks"]=clean["Marks"].fillna(clean["Marks"].median())
clean["Attendance"]=clean["Marks"].fillna(clean["Attendance"].median())
clean["Name"]=clean["Name"].fillna("unknown")
print(clean)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        82.0  2026-09-01
1         102    Aditi           cse   72.0        72.0  10-09-2026
2         102    Aditi           cse   72.0        72.0  01-09-2026
3         103    Arjun  Data Science   82.0        82.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        91.0   not known
5         105  unknown           ECI   88.0        88.0  2026-09-03

Remove exact duplicate

In [19]:
print("Exact duplicates",clean.duplicated().sum())

Exact duplicates 0

In [20]:
clean

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        82.0  2026-09-01
1         102    Aditi           cse   72.0        72.0  10-09-2026
2         102    Aditi           cse   72.0        72.0  01-09-2026
3         103    Arjun  Data Science   82.0        82.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0        91.0   not known
5         105  unknown           ECI   88.0        88.0  2026-09-03

In [21]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    "Student_ID":[101,102,102,103,104,105],
    "Name":["Astha","Aditi","Aditi","Arjun","Krishna",None],
    "Dept":["CSE","cse","cse","Data Science","DATA SCIENCE","ECI"],
    "Marks":[82,72,72,np.nan,91,88],
    "Attendance":[90,82,82,75,np.nan,88],
    "Exam_Date":["2026-09-01","10-09-2026","01-09-2026","2020-09-02","not known","2026-09-03"]
})
print(df)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           CSE   82.0        90.0  2026-09-01
1         102    Aditi           cse   72.0        82.0  10-09-2026
2         102    Aditi           cse   72.0        82.0  01-09-2026
3         103    Arjun  Data Science    NaN        75.0  2020-09-02
4         104  Krishna  DATA SCIENCE   91.0         NaN   not known
5         105     None           ECI   88.0        88.0  2026-09-03

In [22]:
no_exact_duplicates=clean.drop_duplicates()
print("Rows before:",len(clean))
print("Rows after:",len(no_exact_duplicates))

Rows before: 6
Rows after: 6

In [26]:
unique_students=no_exact_duplicates.drop_duplicates(subset=["Student_ID"],keep="last")

fix inconsistent text

In [27]:
unique_students=unique_students.copy()
unique_students["Name"]=(
 unique_students["Name"]
.str.strip()
.str.title()

)
unique_students["Dept"]=(
unique_students["Dept"]
.str.strip()
.str.title()
)
print(unique_students)

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha           Cse   82.0        82.0  2026-09-01
2         102    Aditi           Cse   72.0        72.0  01-09-2026
3         103    Arjun  Data Science   82.0        82.0  2020-09-02
4         104  Krishna  Data Science   91.0        91.0   not known
5         105  Unknown           Eci   88.0        88.0  2026-09-03

In [28]:
c

   Student_ID     Name          Dept  Marks  Attendance   Exam_Date
0         101    Astha  Needs review   82.0        82.0  2026-09-01
2         102    Aditi  Needs review   72.0        72.0  01-09-2026
3         103    Arjun  Needs review   82.0        82.0  2020-09-02
4         104  Krishna  Needs review   91.0        91.0   not known
5         105  Unknown  Needs review   88.0        88.0  2026-09-03

Convert data and check ranges

In [29]:
unique_students["Exam_Date"]=pd.to_datetime(unique_students["Exam_Date"],errors="coerce",dayfirst=True)
print(unique_students)

   Student_ID     Name          Dept  Marks  Attendance  Exam_Date
0         101    Astha  Needs review   82.0        82.0 2026-01-09
2         102    Aditi  Needs review   72.0        72.0        NaT
3         103    Arjun  Needs review   82.0        82.0 2020-02-09
4         104  Krishna  Needs review   91.0        91.0        NaT
5         105  Unknown  Needs review   88.0        88.0 2026-03-09

In [31]:
print(unique_students[["Student_ID","Exam_Date"]])
print("Missing or invalid dates",unique_students["Exam_Date"].isna().sum())

   Student_ID  Exam_Date
0         101 2026-01-09
2         102        NaT
3         103 2020-02-09
4         104        NaT
5         105 2026-03-09
Missing or invalid dates 2

In [33]:
bad_marks=unique_students[~unique_students["Marks"].between(0,100)]
print("Marks outside 0-100:")
print(bad_marks)

Marks outside 0-100:
Empty DataFrame
Columns: [Student_ID, Name, Dept, Marks, Attendance, Exam_Date]
Index: []

In [34]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Marks': ['90', '', 'NA', '80']
})

df['Marks'] = df['Marks'].replace(['', 'NA'], np.nan)

print(df)

  Marks
0    90
1   NaN
2   NaN
3    80

In [35]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D', 'E'],
    'Marks': [80, 90, np.nan, 70, 100]
})

# Method 1: Drop missing rows
df_drop = df.dropna()

print("After dropping:")
print(df_drop)

# Method 2: Fill missing marks with median
df_fill = df.copy()
df_fill['Marks'] = df_fill['Marks'].fillna(df_fill['Marks'].median())

print("After filling with median:")
print(df_fill)

After dropping:
  Student  Marks
0       A   80.0
1       B   90.0
3       D   70.0
4       E  100.0
After filling with median:
  Student  Marks
0       A   80.0
1       B   90.0
2       C   85.0
3       D   70.0
4       E  100.0

In [36]:
import pandas as pd

df = pd.DataFrame({
    'Student_ID': [101, 101, 102, 103, 103],
    'Transaction': ['Books', 'Pen', 'Bag', 'Notebook', 'Pencil']
})

print("Original Data:")
print(df)

# Remove duplicate Student_ID
df_new = df.drop_duplicates(subset=['Student_ID'])

print("\nAfter removing duplicates:")
print(df_new)

Original Data:
   Student_ID Transaction
0         101       Books
1         101         Pen
2         102         Bag
3         103    Notebook
4         103      Pencil

After removing duplicates:
   Student_ID Transaction
0         101       Books
2         102         Bag
3         103    Notebook

In [37]:
import pandas as pd
import numpy as np

# NaN - Missing numerical value
marks = np.nan

# NaT - Missing date/time value
date = pd.NaT

print("NaN:", marks)
print("NaT:", date)

NaN: nan
NaT: NaT

In [38]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [80, np.nan, 90, np.nan]
})

print("Original Data:")
print(df)

# Fill missing values with median
median_marks = df['Marks'].median()
df['Marks'] = df['Marks'].fillna(median_marks)

print("\nCleaned Data:")
print(df)

# Document cleaning decision
print("\nData Cleaning Report:")
print("Missing Marks filled using median:", median_marks)
print("Missing values after cleaning:", df.isnull().sum().sum())

Original Data:
  Student  Marks
0       A   80.0
1       B    NaN
2       C   90.0
3       D    NaN

Cleaned Data:
  Student  Marks
0       A   80.0
1       B   85.0
2       C   90.0
3       D   85.0

Data Cleaning Report:
Missing Marks filled using median: 85.0
Missing values after cleaning: 0

 Data wrangling
 1. MultiIndexing or hierarchial indexing
 2. join
 3. combine
 4. concat
 5. Reshape
 6. pivot

In [41]:
import pandas as pd

In [42]:
# create a unniversity Dataset
students = pd.DataFrame({
    "Student_ID":["S101","S102","S103","S104","S105","S106"],
    "Name":["Amit","Riya","Priya","shashi","Harish","Balaji"],
    "Department":["CSE","DS","CSE","CSE","DS","CSE"],
    "Semester":[3,3,3,2,2,3]
})
print(students)

  Student_ID    Name Department  Semester
0       S101    Amit        CSE         3
1       S102    Riya         DS         3
2       S103   Priya        CSE         3
3       S104  shashi        CSE         2
4       S105  Harish         DS         2
5       S106  Balaji        CSE         3

In [44]:
# create multiIndex
student_index=students.set_index(["Department","Semester","Student_ID"])
print(student_index)

                                  Name
Department Semester Student_ID
CSE        3        S101          Amit
DS         3        S102          Riya
CSE        3        S103         Priya
           2        S104        shashi
DS         2        S105        Harish
CSE        3        S106        Balaji

In [47]:
s_index = students.set_index(["Department","Student_ID"])
print(s_index)

                         Name  Semester
Department Student_ID
CSE        S101          Amit         3
DS         S102          Riya         3
CSE        S103         Priya         3
           S104        shashi         2
DS         S105        Harish         2
CSE        S106        Balaji         3

In [48]:
df_reset = s_index.reset_index()
print(df_reset)

  Department Student_ID    Name  Semester
0        CSE       S101    Amit         3
1         DS       S102    Riya         3
2        CSE       S103   Priya         3
3        CSE       S104  shashi         2
4         DS       S105  Harish         2
5        CSE       S106  Balaji         3

In [49]:
s_index.swaplevel("Student_ID","Department")

                         Name  Semester
Student_ID Department
S101       CSE           Amit         3
S102       DS            Riya         3
S103       CSE          Priya         3
S104       CSE         shashi         2
S105       DS          Harish         2
S106       CSE         Balaji         3

In [50]:
s_index.loc["CSE"]

              Name  Semester
Student_ID
S101          Amit         3
S103         Priya         3
S104        shashi         2
S106        Balaji         3

In [ ]:
#join
#1. students_info
#2. Examination system
#3. Attendance

In [53]:
#Create Examination Table
exam=({
    "Student_ID":["S101","S102","S103","S105"],
    "Internal":[82,75,90,68],
    "Final":[88,72,94,70]
})
print(exam)

{'Student_ID': ['S101', 'S102', 'S103', 'S105'], 'Internal': [82, 75, 90, 68], 'Final': [88, 72, 94, 70]}

In [52]:
# create student table
student_info = pd.DataFrame({
    "Student_ID":["S101","S102","S103","S104"],
    "Name":["Anu","Ravi","Priya","Arun"],
    "Department":["CSE","CSE","DS","DS"]
})
print(student_info)

  Student_ID   Name Department
0       S101    Anu        CSE
1       S102   Ravi        CSE
2       S103  Priya         DS
3       S104   Arun         DS